[2023-01-05 02:54:00,467] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: btc_data_pipeline_dag.download_stock_data_from_datalake_task manual__2023-01-05T02:53:58.242190+00:00 [queued]>
[2023-01-05 02:54:00,480] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: btc_data_pipeline_dag.download_stock_data_from_datalake_task manual__2023-01-05T02:53:58.242190+00:00 [queued]>
[2023-01-05 02:54:00,480] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-05 02:54:00,480] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-05 02:54:00,480] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-05 02:54:00,494] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): download_stock_data_from_datalake_task> on 2023-01-05 02:53:58.242190+00:00
[2023-01-05 02:54:00,502] {standard_task_runner.py:52} INFO - Started process 149 to run task
[2023-01-05 02:54:00,510] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'btc_data_pipeline_dag', 'download_stock_data_from_datalake_task', 'manual__2023-01-05T02:53:58.242190+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/btc_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpyxnkdpcu', '--error-file', '/tmp/tmp2gqdxeyy']
[2023-01-05 02:54:00,512] {standard_task_runner.py:80} INFO - Job 43: Subtask download_stock_data_from_datalake_task
[2023-01-05 02:54:00,581] {task_command.py:370} INFO - Running <TaskInstance: btc_data_pipeline_dag.download_stock_data_from_datalake_task manual__2023-01-05T02:53:58.242190+00:00 [running]> on host 94450fd8b415
[2023-01-05 02:54:00,664] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=btc_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=download_stock_data_from_datalake_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-05T02:53:58.242190+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-05T02:53:58.242190+00:00
[2023-01-05 02:54:03,778] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Load_Current_SP_500_End_of_Day_Prices_Into_GCS.py", line 61, in main
    beg_date, end_date = date_range(ticker)
  File "/opt/airflow/dags/Load_Current_SP_500_End_of_Day_Prices_Into_GCS.py", line 31, in date_range
    for row in job.result():
  File "/home/airflow/.local/lib/python3.9/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.9/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Unrecognized name: MMM at [3:28]

Location: us-central1
Job ID: e500c87b-7337-4f39-be4d-bf7d82ac5858

[2023-01-05 02:54:03,792] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=btc_data_pipeline_dag, task_id=download_stock_data_from_datalake_task, execution_date=20230105T025358, start_date=20230105T025400, end_date=20230105T025403
[2023-01-05 02:54:03,805] {standard_task_runner.py:92} ERROR - Failed to execute job 43 for task download_stock_data_from_datalake_task (400 Unrecognized name: MMM at [3:28]

Location: us-central1
Job ID: e500c87b-7337-4f39-be4d-bf7d82ac5858
; 149)
[2023-01-05 02:54:03,824] {local_task_job.py:156} INFO - Task exited with return code 1
