[2023-01-05 22:55:03,032] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: btc_data_pipeline_dag.download_stock_data_from_datalake_task scheduled__2023-01-04T22:55:00+00:00 [queued]>
[2023-01-05 22:55:03,041] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: btc_data_pipeline_dag.download_stock_data_from_datalake_task scheduled__2023-01-04T22:55:00+00:00 [queued]>
[2023-01-05 22:55:03,041] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-05 22:55:03,041] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-05 22:55:03,041] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-05 22:55:03,054] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): download_stock_data_from_datalake_task> on 2023-01-04 22:55:00+00:00
[2023-01-05 22:55:03,062] {standard_task_runner.py:52} INFO - Started process 3128 to run task
[2023-01-05 22:55:03,066] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'btc_data_pipeline_dag', 'download_stock_data_from_datalake_task', 'scheduled__2023-01-04T22:55:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/btc_data_pipeline_dag.py', '--cfg-path', '/tmp/tmp41mxh6c0', '--error-file', '/tmp/tmp5xsxl233']
[2023-01-05 22:55:03,068] {standard_task_runner.py:80} INFO - Job 63: Subtask download_stock_data_from_datalake_task
[2023-01-05 22:55:03,133] {task_command.py:370} INFO - Running <TaskInstance: btc_data_pipeline_dag.download_stock_data_from_datalake_task scheduled__2023-01-04T22:55:00+00:00 [running]> on host 7aa3417b2d87
[2023-01-05 22:55:03,205] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=btc_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=download_stock_data_from_datalake_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T22:55:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-04T22:55:00+00:00
[2023-01-05 22:55:04,524] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Load_Current_BTC_End_of_Day_Prices_Into_GCS.py", line 43, in main
    beg_date, end_date = date_range()
  File "/opt/airflow/dags/Load_Current_BTC_End_of_Day_Prices_Into_GCS.py", line 18, in date_range
    assert beg_date < datetime.today(), "Beginning Date is in the Future"
AssertionError: Beginning Date is in the Future
[2023-01-05 22:55:04,545] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=btc_data_pipeline_dag, task_id=download_stock_data_from_datalake_task, execution_date=20230104T225500, start_date=20230105T225503, end_date=20230105T225504
[2023-01-05 22:55:04,565] {standard_task_runner.py:92} ERROR - Failed to execute job 63 for task download_stock_data_from_datalake_task (Beginning Date is in the Future; 3128)
[2023-01-05 22:55:04,608] {local_task_job.py:156} INFO - Task exited with return code 1
