[2023-01-05 23:20:42,273] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.upload_btc_data_to_datalake_task manual__2023-01-05T23:20:40.418448+00:00 [queued]>
[2023-01-05 23:20:42,282] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stock_data_pipeline_dag.upload_btc_data_to_datalake_task manual__2023-01-05T23:20:40.418448+00:00 [queued]>
[2023-01-05 23:20:42,282] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-05 23:20:42,283] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-05 23:20:42,283] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-05 23:20:42,295] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_btc_data_to_datalake_task> on 2023-01-05 23:20:40.418448+00:00
[2023-01-05 23:20:42,302] {standard_task_runner.py:52} INFO - Started process 4082 to run task
[2023-01-05 23:20:42,307] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stock_data_pipeline_dag', 'upload_btc_data_to_datalake_task', 'manual__2023-01-05T23:20:40.418448+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_pipeline_dag.py', '--cfg-path', '/tmp/tmp2z7yvw00', '--error-file', '/tmp/tmpsjlk2275']
[2023-01-05 23:20:42,308] {standard_task_runner.py:80} INFO - Job 69: Subtask upload_btc_data_to_datalake_task
[2023-01-05 23:20:42,382] {task_command.py:370} INFO - Running <TaskInstance: stock_data_pipeline_dag.upload_btc_data_to_datalake_task manual__2023-01-05T23:20:40.418448+00:00 [running]> on host 7aa3417b2d87
[2023-01-05 23:20:42,460] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stock_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=upload_btc_data_to_datalake_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-05T23:20:40.418448+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-05T23:20:40.418448+00:00
[2023-01-05 23:20:45,618] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Load_Current_SP_500_End_of_Day_Prices_Into_GCS.py", line 61, in main
    beg_date, end_date = date_range(ticker)
  File "/opt/airflow/dags/Load_Current_SP_500_End_of_Day_Prices_Into_GCS.py", line 31, in date_range
    for row in job.result():
  File "/home/airflow/.local/lib/python3.9/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.9/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Unrecognized name: MMM at [3:28]

Location: us-central1
Job ID: df794596-56f4-4ccb-b97c-56c89b6b2bee

[2023-01-05 23:20:45,629] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=stock_data_pipeline_dag, task_id=upload_btc_data_to_datalake_task, execution_date=20230105T232040, start_date=20230105T232042, end_date=20230105T232045
[2023-01-05 23:20:45,641] {standard_task_runner.py:92} ERROR - Failed to execute job 69 for task upload_btc_data_to_datalake_task (400 Unrecognized name: MMM at [3:28]

Location: us-central1
Job ID: df794596-56f4-4ccb-b97c-56c89b6b2bee
; 4082)
[2023-01-05 23:20:45,685] {local_task_job.py:156} INFO - Task exited with return code 1
